eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 2 #契约更新间隔
    lease-expiration-duration-in-seconds: 4 #契约过期时间
    hostname: localhost
server:
  port: 10001
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - 192.168.1.159:9000
            - 192.168.1.159:9001
            - 192.168.1.159:9002
          zkNodes: 192.168.1.159:2181
management:
  security:
    enabled: false
tips: 1111
