server:
  port: 7902
spring:
  application:
    name: producer-server
 # cloud:
      #   config:
      #uri: http://localhost:1000
      #discovery:
      # enabled: true
      #service-id: consumer-server # 配置中心的spring.application.name
    #fail-fast: true # 如果连接配置中心出错,则中断程序
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
zuul:
  routes:
    producer-server:
      path: /producer-server:/**
      serviceId: producer-server










