spring:
  profiles:
    active: dev
  cloud:
    config:

      server:
        git:
          uri: https://github.com/lwb711229/springclouddemo.git
          username: lwb711229
          password: wander711229
          searchPaths: '{profile}'
