spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://rdc.hand-china.com/gitlab/15433/config1314.git
          username: 15s433
          password: Wangliguo1995
          searchPaths: '{profile}'
